### ISSUE TITLE
Error when trying to compile and run

### ISSUE THREAD

**Issue by Fusion-Tech-05** [zerasul/genesis-code#1061]
![image](https://github.com/zerasul/genesis-code/assets/87595770/4800215d-3f74-4834-ac1d-643cd5374934)
It fails to compile and run when using Ctrl Shift P then using the 'Genesis Code : Compile and Run' option. gives me and error indicating something is wrong with the && symbol.

**Comment by zerasul** [comment]
Hi:

Its seems that you are using Powershell as terminal; genesis code works with CMD Prompt. To change the default terminal you can follow the next instructions:

1. Change default terminal, using the command >Terminal: Select default Profile and select Command Prompt (cmd).

Or you can select the default profile clicking on the following button:

![imagen](https://github.com/zerasul/genesis-code/assets/6067824/742ab802-6c5f-475e-9331-b9e7c7e450b3)

And click on the option "Select default profile", later select CMD.

**Comment by Fusion-Tech-05** [comment]
Thank you so much. I really appreciate you helping me. Can you please help me with this error, I am really not used to visual studio code or setting up a development environment in general.
![image](https://github.com/zerasul/genesis-code/assets/87595770/ec3e7f2e-4ed8-45e9-831e-2cf4a3e54a9e)
I am trying to use SGDK if that helps.

**Comment by zerasul** [comment]
Hi:

Its seems you cannot configure the ``GDK``` environment variable.  You can set this variable in two ways:

1. Setting the GDK environment variable on your system.
2. Set the GDK environment variable on Genesis Code configuration (press <kbd>ctrl</kbd>+<kbd>,</kbd> and see the options under extensions-> Genesis Code.

I hope this can helps you.

**Comment by Fusion-Tech-05** [comment]
What is the GDK variable for?

**Comment by zerasul** [comment]
The GDK Variable points to you SGDK installation folder.

**Comment by Fusion-Tech-05** [comment]
Oh, okay, I understand now, thank you so much.

**Comment by zerasul** [comment]
You are welcome.

I you have more questions about Genesis code; you can check the Documentation:

https://zerasul.github.io/genesis-code-docs/

**Comment by Fusion-Tech-05** [comment]
Thanks.
