### ISSUE TITLE
add an about genesis code Dialog

### ISSUE THREAD

**Issue by zerasul** [zerasul/genesis-code#207]
add an about genesis code dialog with information about the extension and some useful links, like:

* extension web page
* how to contribute
* version information
* author information.

**Comment by michaeltintiuc** [comment]
Where exactly were you thinking of adding it?

**Comment by zerasul** [comment]
hi; @michaeltintiuc :

Im thinking in add a "about Genesis code" Dialog; in this case we can use the status bar notification text with "genesis code ready"; and after click on it a Dialog appears with the next information:

* Genesis Code Version
* Author/s information. We can use a link to github insight of the proyect.
* Extensión documentation link -> https://zerasul.github.io/genesis-code-docs/
* Genesis code Github Link 
* more usefull information
