### ISSUE TITLE
TMXParser.js - Activating extension 'Zerasul.genesis-code' failed: Cannot find module 'fast-xml-parser'

### ISSUE THREAD

**Issue by PointerOffset** [zerasul/genesis-code#216]
I'm unable to load the Genesis Code extension. Version is 1.3.0 and my VSCode version details are:

```
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

When attempting to run any Genesis Code command, I receive and error that the command isn't found. On startup, the dev console spits out this error and stack trace indicating a failure to activate the extension:

```
Activating extension 'Zerasul.genesis-code' failed: Cannot find module 'fast-xml-parser'
Require stack:
- c:\Users\mc\.vscode\extensions\zerasul.genesis-code-1.3.0\out\TmxParser.js
- c:\Users\mc\.vscode\extensions\zerasul.genesis-code-1.3.0\out\appModel.js
- c:\Users\mc\.vscode\extensions\zerasul.genesis-code-1.3.0\out\extension.js
- c:\Users\mc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\mc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\mc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

I've tried uninstalling the extension, removing the installation files from my user directory .vscode/extensions folder, and reinstalling. Unfortunately it hasn't resolved the issue. So for some reason, the `fast-xml-parser` NPM package either isn't being installed or isn't being detected.

**Comment by zerasul** [comment]
Thanks for the issue. Let me check why the module is not loaded.

**Comment by PointerOffset** [comment]
Awesome! Just updated to 1.3.1 and it's working just fine now. Thanks for the quick fix! 👍
