### ISSUE TITLE
Cannot resolve %GDK%

### ISSUE THREAD

**Issue by Ravenheart** [zerasul/genesis-code#223]
```sh
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\dev\genesis\megapong> set GDK=D:\dev\genesis\tools\sgdk
PS D:\dev\genesis\megapong> %GDK%\bin\make -f %GDK%\makefile.gen
%GDK%\bin\make : The module '%GDK%' could not be loaded. For more information, run 'Import-Module %GDK%'.
At line:1 char:1
+ %GDK%\bin\make -f %GDK%\makefile.gen
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (%GDK%\bin\make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule
 
PS D:\dev\genesis\megapong>
```

I have correctly setup SGDK and have correct GDK and GDK_WIN variables and infact if I run the following command everything works fine.
```sh
cmd /C %GDK%\bin\make -f %GDK%\makefile.gen
```

I am using the latest Windows 10 Pro x64 and VSCode, Genesis Code is 1.3.1

**Comment by zerasul** [comment]
hi; it seems that is an error to use PowerShell. Try to configure your vscode for use CMD instead.

Im going to implement in the next versions, the use of powershell or CMD.

**Comment by Ravenheart** [comment]
I switched to Command Prompt and now i get the followign error:
```sh
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

D:\dev\genesis\megapong>set GDK=D:\dev\genesis\tools\sgdk

D:\dev\genesis\megapong>%GDK%\bin\make -f %GDK%\makefile.gen
D:\dev\genesis\tools\sgdk/bin/mkdir -p src/boot
D:\dev\genesis\tools\sgdk/bin/sh: D:devgenesistoolssgdk/bin/mkdir: No such file or directory
make: *** [pre-build] Error 127

D:\dev\genesis\megapong>

```

**Comment by zerasul** [comment]
what version of SGDK are you using??

**Comment by Ravenheart** [comment]
SGDK 1.51 (april 2020), I think the problem is it expect it with forward-slashes (like on linux) rather than backslashes.

**Comment by JuanjoSalvador** [comment]
Same error here. I'm trying to make a workaround by setting GDK and GDK_WIN environment variables on PowerShell, but that could create other problems...
