### ISSUE TITLE
The Compile Project command not starting in portable mode after a restarting VS code

### ISSUE THREAD

**Issue by werton** [zerasul/genesis-code#859]
The Compile Project command not starting in portable mode after a restarting VS code (just nothing happens, although before the restart the compilation started ok), but at the same time the emulator starts (If execute Compile & Run Project - compiling is ignoring and only execute start of emulator). Uninstalling and reinstalling the extension helps, but the next time you restart vs code, everything is repeated.

**Comment by zerasul** [comment]
Hi @werton :

Can you tell me what version of VScode are you using?

We know that there is a bug that repeat the "gens Code" terminals and you can see lot of terminals. Can you check that you can see the compilation process in one of this terminals?

We are going to check how to repeat the situation that you describe; but if  you can bring us more information, we will apreciate it.

Thanks.

**Comment by werton** [comment]
Hi @zerasul 
VS code 1.70.2 

> We know that there is a bug that repeat the "gens Code" terminals and you can see lot of terminals. Can you check that you can see the compilation process in one of this terminals?
Yes, that seems to be the case. With each restart, 1 more gens.code terminal is added and if you switch to the top, the compilation process is visible.
