### ISSUE TITLE
Improve support for SGDK 2.00

### ISSUE THREAD

**Issue by zerasul** [zerasul/genesis-code#928]
Check documentation and changes for new release of SGDK 2.00

https://github.com/Stephane-D/SGDK/releases/tag/v2.00

**Comment by burmaraider** [comment]
I don't think the extension needs any updating to reflect any of these changes in 1.90 after having a quick browse.

**Comment by zerasul** [comment]
Yes you are rigth; in a first view; the extension works properly for SGDK 1.90. But we need to check that all the rescomp.txt info is not changed for include in the contextual help for the .res editor.

In the files of the extension you can see https://github.com/zerasul/genesis-code/blob/master/resources/codecompletion.json whith the code completion help for the editor.
